server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Polpsi/SpringLevel2Config.git
          search-paths: SpringLevel2/shop2
          clone-on-start: true
  application:
    name: config_server

logging:
  level:
    org.springframework.cloud: DEBUG